### ISSUE TITLE
Concepts ID as URL rather than Literals

### ISSUE THREAD

**Issue by pabloalarconm** [ejp-rd-vp/vp-api-specs#19]
At `CatalogAlphanumericRequestFilter`, the concepts ID are described as Literals but based on the table, this concepts IDs are ontological terms. Example: https://github.com/ejp-rd-vp/vp-api-specs/blob/cb794db0fba58b64d22a1828b7b862897739a47b/individuals_api_v0.2.yml#L253

Also, at some parts of the Catalog descriptions, the Common data elements (CDE) are mentioned, but CDE are only related to /individual calls, but to any /catalog call.

**Comment by rini21** [comment]
Dear Pablo, thanks for keeping us sharp! I have taken the necessary steps to address the concern related to Common Data Elements (CDEs) in the context of catalogs. References to CDEs have been removed from the catalog descriptions as they are indeed specific to /individual calls and not relevant to /catalog calls.

Regarding the classification of resource types in the list of filters, @svituz has indicated that it should be an alphanumeric filter (both in the list of filters and in the example). However, there seems to be some ambiguity around whether this should be an ontological term. It would greatly assist us if you could provide further clarification on this matter.
