### ISSUE TITLE
resultSets object in individual/catalog response and other elements

### ISSUE THREAD

**Issue by pabloalarconm** [ejp-rd-vp/vp-api-specs#21]
In ``resultSets`` object from [OpenAPI specification](https://github.com/ejp-rd-vp/vp-api-specs/blob/main/individuals_api_v0.2.yml). There's several elements at /catalog responses that are mandatory based on the spec, but not used in the documentation example from README.md. It seems there's a misalignment between the usage documentation and the spec. Like, for example `ReturnedSchema`, where only two elements are defined in the spec, but 5 appeared in the example from the README.md.

In relation to /individual response: it retrieves more information than counts or bool information that inform about the data existence, and CDE implementation is incapable of retrieving this additional information like contact information and result identifiers. Only ``responseSummary`` object is needed to retrieve bool/count information. 

In relation to /catalog response, something similar happens, some properties (some of them mandatory, other not) are not covered by the metadata model, so are impossible to be retrive in a catalog response. This situation requires a review to be aligned with the specification and the documentation. Right now, `CatalogResult`object because it doesn't fit.

**Comment by rini21** [comment]
Hey Pablo,

You're absolutely right about the misalignment between the Readme and the spec. I've taken steps to address this in [version 2.0 ](https://app.swaggerhub.com/apis/VM172_1/vp_individuals/v2.0)of the spec, so it should be more accurate now.

Regarding the /individuals endpoint, we've made the 'response' optional, but we should have a deeper conversation about this. Retrieving contact information is important for guiding users from VP-Platform to the discovered resource, so we'll need to figure out the best way to handle that.
![image](https://github.com/ejp-rd-vp/vp-api-specs/assets/24955128/b4972b76-5e0d-496e-a9bd-f5a65bf49c87)

As for the /catalogs endpoint, it might be a good idea to discuss this further with @svituz and the Beacon group in future meetings. Aligning it with the specification and documentation is definitely a priority.

Thanks for your vigilance in keeping things on track!
